const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path'); const fs = require('fs'); const { spawn } = require('child_process'); const https = require('https'); const { searchWeb } = require('./web-search');
const cryptoEngine = require('./crypto');
const { PermissionPolicy } = require('./permissions/policy'); const { PermissionManager } = require('./permissions/manager'); const { AgentController } = require('./agent/controller'); const { DeveloperEngine } = require('./developer-engine/engine'); const { DesktopStorage } = require('./desktop-storage');
const { createCivilizationRuntime } = require('./civilization-core/runtime'); const { registerGovernanceIPC } = require('./civilization-core/governance/ipc');
const dataDir=path.join(app.getPath('userData'),'localmind'),memoryFile=path.join(dataDir,'memory.json'),settingsFile=path.join(dataDir,'settings.json'),bootstrapFile=path.join(dataDir,'bootstrap.json'),webCacheFile=path.join(dataDir,'web-cache.json');
const DEFAULT_MODEL='qwen3:4b';
const permissionManager=new PermissionManager(new PermissionPolicy({network:'ask',filesystemRead:'ask',filesystemWrite:'ask',codeExecution:'ask',processExecution:'deny',installSoftware:'deny',systemChanges:'deny'}));
const agentController=new AgentController({permissionManager}); const developerEngine=new DeveloperEngine({permissionManager});
const civilization=createCivilizationRuntime({appVersion:'9.3'}); registerGovernanceIPC(ipcMain,civilization); civilization.bootstrap();
const OLLAMA_URL='http://127.0.0.1:11434';
const OLLAMA_CANDIDATES=()=>[path.join(process.env.LOCALAPPDATA||'', 'Programs','Ollama','ollama.exe'),path.join(process.env.LOCALAPPDATA||'', 'Ollama','ollama.exe'),path.join(process.env.ProgramFiles||'C:\\Program Files','Ollama','ollama.exe')].filter(Boolean);
let ollamaReadyPromise=null; const desktopStorage = new DesktopStorage({ dataDir });
function ensureData(){fs.mkdirSync(dataDir,{recursive:true});if(!fs.existsSync(memoryFile))fs.writeFileSync(memoryFile,JSON.stringify({memories:[]},null,2));if(!fs.existsSync(settingsFile))fs.writeFileSync(settingsFile,JSON.stringify({endpoint:OLLAMA_URL,model:DEFAULT_MODEL,provider:'auto',internet:true,autoLearn:true},null,2));if(!fs.existsSync(webCacheFile))fs.writeFileSync(webCacheFile,JSON.stringify({pages:[]},null,2));}
function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;}} function writeJson(file,value){fs.writeFileSync(file,JSON.stringify(value,null,2));}
function getSettings(){const value=readJson(settingsFile,{endpoint:OLLAMA_URL,model:DEFAULT_MODEL,provider:'auto',internet:true,autoLearn:true});const endpoint=String(value.endpoint||OLLAMA_URL).trim();const isLocalHttp=endpoint===OLLAMA_URL||endpoint.startsWith(`${OLLAMA_URL}/`);if(!isLocalHttp)value.endpoint=OLLAMA_URL;value.model=String(value.model||DEFAULT_MODEL);value.provider=['auto','ollama','openai','gemini','claude','openrouter','lmstudio'].includes(value.provider)?value.provider:'auto';value.internet=value.internet!==false;value.autoLearn=value.autoLearn!==false;return value;}
function getMemory(){return readJson(memoryFile,{memories:[]});} function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function downloadFile(url,destination){return new Promise((resolve,reject)=>{const file=fs.createWriteStream(destination);https.get(url,response=>{if(response.statusCode>=300&&response.statusCode<400&&response.headers.location){file.close();fs.unlink(destination,()=>{});return downloadFile(response.headers.location,destination).then(resolve,reject);}if(response.statusCode!==200){file.close();fs.unlink(destination,()=>{});return reject(new Error(`Download HTTP ${response.statusCode}`));}response.pipe(file);file.on('finish',()=>file.close(resolve));}).on('error',err=>{file.close();fs.unlink(destination,()=>{});reject(err);});});}
function run(exe,args,options={}){return new Promise((resolve,reject)=>{const child=spawn(exe,args,{windowsHide:true,...options});let stdout='',stderr='';const timer=setTimeout(()=>{try{child.kill();}catch{}reject(new Error(`${exe} timed out`));},options.timeoutMs||600000);child.stdout?.on('data',d=>stdout+=d);child.stderr?.on('data',d=>stderr+=d);child.on('error',e=>{clearTimeout(timer);reject(e);});child.on('close',code=>{clearTimeout(timer);code===0?resolve({stdout,stderr}):reject(new Error(`${exe} exited ${code}: ${stderr||stdout}`));});});}
function findOllama(){return OLLAMA_CANDIDATES().find(p=>fs.existsSync(p))||'ollama.exe';} function ollamaInstalled(){return findOllama()!=='ollama.exe';}
async function waitForOllama(timeout=45000){const t=Date.now();while(Date.now()-t<timeout){try{const r=await fetch(`${OLLAMA_URL}/api/tags`);if(r.ok)return true;}catch{}await sleep(1000);}throw new Error(`Ollama не отвечает на ${OLLAMA_URL}`);}
async function ensureOllamaAndModel(sendStatus){ensureData();try{let exe=findOllama();if(!ollamaInstalled())throw new Error('Ollama не установлен');sendStatus?.('Запускаю Ollama…');try{const probe=await fetch(`${OLLAMA_URL}/api/tags`);if(!probe.ok)throw new Error('not ready');}catch{const p=spawn(exe,['serve'],{windowsHide:true,detached:true,stdio:'ignore'});p.unref();}await waitForOllama();sendStatus?.(`Проверяю модель ${DEFAULT_MODEL}…`);const tags=await(await fetch(`${OLLAMA_URL}/api/tags`)).json();if(!(tags.models||[]).some(m=>m.name===DEFAULT_MODEL)){sendStatus?.(`Скачиваю модель ${DEFAULT_MODEL}…`);await run(exe,['pull',DEFAULT_MODEL],{timeoutMs:1800000});}writeJson(bootstrapFile,{ready:true,model:DEFAULT_MODEL,completedAt:new Date().toISOString()});sendStatus?.('Ollama готов.');return true;}catch(e){writeJson(bootstrapFile,{ready:false,error:e.message,at:new Date().toISOString()});return false;}}
async function ensureOllamaReady(sendStatus){if(!ollamaReadyPromise)ollamaReadyPromise=ensureOllamaAndModel(sendStatus).finally(()=>{ollamaReadyPromise=null;});if(!await ollamaReadyPromise)throw new Error(readJson(bootstrapFile,{error:'Ollama не готов.'}).error);return true;}
async function ollama(messages){const s=getSettings();const r=await fetch(`${OLLAMA_URL}/api/chat`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:s.model||DEFAULT_MODEL,messages,stream:false})});if(!r.ok)throw new Error(`Ollama HTTP ${r.status}: ${await r.text()}`);const data=await r.json();return data.message?.content||'';}
async function openai(messages){const key=process.env.OPENAI_API_KEY;if(!key)throw new Error('OPENAI_API_KEY не задан');const input=messages.map(m=>`${m.role.toUpperCase()}: ${m.content}`).join('\n\n');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5',input})});if(!r.ok)throw new Error(`OpenAI HTTP ${r.status}: ${await r.text()}`);const data=await r.json();return data.output_text||'';}
async function gemini(messages){const key=process.env.GEMINI_API_KEY;if(!key)throw new Error('GEMINI_API_KEY не задан');const contents=messages.map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]}));const model=process.env.GEMINI_MODEL||'gemini-2.5-flash';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents})});if(!r.ok)throw new Error(`Gemini HTTP ${r.status}: ${await r.text()}`);const data=await r.json();return data.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';}
function providerAvailability(){return {ollama:ollamaInstalled(),openai:Boolean(process.env.OPENAI_API_KEY),gemini:Boolean(process.env.GEMINI_API_KEY),claude:Boolean(process.env.ANTHROPIC_API_KEY),openrouter:Boolean(process.env.OPENROUTER_API_KEY),lmstudio:false};}
async function generateAI(messages,sendStatus){const s=getSettings();const available=providerAvailability();const order=s.provider==='auto'?['ollama','openai','gemini','claude','openrouter','lmstudio']:[s.provider];for(const provider of order){if(provider==='ollama'&&available.ollama){try{await ensureOllamaReady(sendStatus);return {provider,text:await ollama(messages)};}catch(e){sendStatus?.(`Ollama недоступен: ${e.message}`);continue;}}if(provider==='openai'&&available.openai){try{return {provider,text:await openai(messages)};}catch(e){sendStatus?.(`OpenAI недоступен: ${e.message}`);continue;}}if(provider==='gemini'&&available.gemini){try{return {provider,text:await gemini(messages)};}catch(e){sendStatus?.(`Gemini недоступен: ${e.message}`);continue;}}}throw new Error('Нет доступного AI-провайдера.');}
function learnFromConversation(user,assistant,source='conversation'){generateAI([{role:'system',content:'You are a memory curator. Return JSON array only.'},{role:'user',content:`Extract durable non-sensitive facts/preferences. SOURCE:${source}\n${user}\n${assistant}`}]).then(({text})=>{try{const items=JSON.parse(text.replace(/```json|```/g,'').trim());if(Array.isArray(items)){const db=getMemory();for(const item of items.slice(0,8)){const t=String(item).trim();if(t&&!db.memories.includes(t))db.memories.push(t);}writeJson(memoryFile,{memories:db.memories.slice(-5000)});}}catch{}}).catch(()=>{});}
async function researchAndLearn(query){const s=getSettings();if(!s.internet)return null;try{return await searchWeb(query);}catch{return null;}}
ipcMain.handle('crypto:market',(_,args)=>cryptoEngine.market(args?.symbol,args?.interval,args?.limit));
ipcMain.handle('crypto:onchain',(_,args)=>cryptoEngine.onchain(args?.symbol));
ipcMain.handle('crypto:news',(_,args)=>cryptoEngine.news(args?.query,args?.limit));
ipcMain.handle('crypto:backtest',(_,args)=>cryptoEngine.backtest(args?.candles||[],args?.strategy||{}));
ipcMain.handle('crypto:analyze',async(_,args)=>{const market=await cryptoEngine.market(args?.symbol||'BTCUSDT',args?.interval||'1d',args?.limit||365);const coin=await cryptoEngine.onchain(args?.coin||'bitcoin');const news=await cryptoEngine.news(args?.query||args?.coin||'bitcoin cryptocurrency',10);const prompt=`Analyze cryptocurrency data. Distinguish raw facts from interpretation. Do not promise returns. MARKET:${JSON.stringify(market)}\nONCHAIN:${JSON.stringify(coin).slice(0,30000)}\nNEWS:${JSON.stringify(news)}`;const ai=await generateAI([{role:'system',content:'You are a crypto research analyst. Be evidence-based and explicit about uncertainty.'},{role:'user',content:prompt}]);return {market,onchain:coin,news,analysis:ai.text,provider:ai.provider};});
ipcMain.handle('agent:plan',async(_,task)=>agentController.plan(task)); ipcMain.handle('permissions:list',()=>permissionManager.listPending()); ipcMain.handle('permissions:decide',(_, {id,approved})=>permissionManager.decide(id,Boolean(approved))); ipcMain.handle('agent:execute-python',async(_, {code,timeoutMs})=>agentController.executePython(code,{timeoutMs}));
ipcMain.handle('developer:inspect',()=>{const project=desktopStorage.state().projectPath;return developerEngine.inspect(project&&fs.existsSync(project)?project:undefined);}); ipcMain.handle('developer:plan',(_,task)=>developerEngine.plan(task)); ipcMain.handle('developer:validate',(_,options)=>developerEngine.validate(options||{})); ipcMain.handle('developer:run',async(_, {task,build=false})=>{const project=desktopStorage.state().projectPath;return developerEngine.autonomousCycle({task,build:Boolean(build),root:project&&fs.existsSync(project)?project:undefined});}); ipcMain.handle('developer:cycle',async(_, payload)=>{const project=desktopStorage.state().projectPath;return developerEngine.autonomousCycle({...payload,root:payload?.root||(project&&fs.existsSync(project)?project:undefined)});});
ipcMain.handle('project:choose',()=>desktopStorage.chooseProject()); ipcMain.handle('project:state',()=>desktopStorage.state()); ipcMain.handle('project:reveal',(_,target)=>desktopStorage.reveal(target)); ipcMain.handle('storage:choose',()=>desktopStorage.chooseStorage()); ipcMain.handle('storage:state',()=>desktopStorage.state()); ipcMain.handle('storage:list',()=>desktopStorage.list()); ipcMain.handle('storage:import',()=>desktopStorage.importFiles()); ipcMain.handle('storage:saveText',(_,relativePath,content)=>desktopStorage.saveText(relativePath,content)); ipcMain.handle('storage:open',(_,relativePath)=>desktopStorage.openItem(relativePath)); ipcMain.handle('storage:reveal',(_,relativePath)=>desktopStorage.reveal(desktopStorage.safe(desktopStorage.readState().storagePath,relativePath)));
ipcMain.handle('bootstrap:status',()=>readJson(bootstrapFile,{ready:false})); ipcMain.handle('bootstrap:start',async event=>ensureOllamaReady(msg=>event.sender.send('bootstrap:progress',msg))); ipcMain.handle('settings:get',()=>({...getSettings(),providers:providerAvailability()})); ipcMain.handle('settings:set',(_,value)=>{const next={...getSettings(),internet:Boolean(value.internet),autoLearn:Boolean(value.autoLearn),provider:['auto','ollama','openai','gemini','claude','openrouter','lmstudio'].includes(value.provider)?value.provider:'auto',endpoint:OLLAMA_URL,model:DEFAULT_MODEL};writeJson(settingsFile,next);return {...next,providers:providerAvailability()};}); ipcMain.handle('memory:get',()=>getMemory().memories); ipcMain.handle('memory:clear',()=>{writeJson(memoryFile,{memories:[]});return [];});
ipcMain.handle('chat',async(event,payload)=>{const s=getSettings();let web='';if(s.internet&&payload.allowWeb!==false)web=await researchAndLearn(payload.message)||'';const memory=getMemory().memories.slice(-100).join('\n- ');const project=desktopStorage.state();const system=`You are LocalMind, a private desktop AI assistant.\nMEMORY:\n- ${memory||'(empty)'}\nPROJECT:\n${project.projectPath||'(not selected)'}\nWEB RESEARCH:\n${web||'(none)'}`;const result=await generateAI([{role:'system',content:system},...(payload.history||[]),{role:'user',content:payload.message}],msg=>event.sender.send('bootstrap:progress',msg));if(s.autoLearn)learnFromConversation(payload.message,result.text,web?'conversation+web':'conversation');return result.text;});
ipcMain.handle('test',async()=>{const result=await generateAI([{role:'user',content:'Reply with OK.'}]);return result.provider;});
function createWindow(){ensureData();const win=new BrowserWindow({width:1180,height:820,minWidth:900,minHeight:650,backgroundColor:'#101318',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile('index.html');win.webContents.once('did-finish-load',()=>{const p=providerAvailability();win.webContents.send('bootstrap:progress',p.ollama?'Ollama доступен.':'Ollama не установлен — можно использовать облачные провайдеры.');});}
app.whenReady().then(()=>{createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});}); app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});
