const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path'); const fs = require('fs'); const { spawn } = require('child_process'); const https = require('https'); const { searchWeb } = require('./web-search');
const { PermissionPolicy } = require('./permissions/policy'); const { PermissionManager } = require('./permissions/manager'); const { AgentController } = require('./agent/controller'); const { DeveloperEngine } = require('./developer-engine/engine');
const { createCivilizationRuntime } = require('./civilization-core/runtime'); const { registerGovernanceIPC } = require('./civilization-core/governance/ipc');
const dataDir=path.join(app.getPath('userData'),'localmind'),memoryFile=path.join(dataDir,'memory.json'),settingsFile=path.join(dataDir,'settings.json'),bootstrapFile=path.join(dataDir,'bootstrap.json'),webCacheFile=path.join(dataDir,'web-cache.json');
const DEFAULT_MODEL='qwen3:4b';
const permissionManager=new PermissionManager(new PermissionPolicy({network:'ask',filesystemRead:'ask',filesystemWrite:'ask',codeExecution:'ask',processExecution:'deny',installSoftware:'deny',systemChanges:'deny'}));
const agentController=new AgentController({permissionManager});
const developerEngine=new DeveloperEngine({permissionManager});
const civilization=createCivilizationRuntime({appVersion:'9.3'}); registerGovernanceIPC(ipcMain,civilization); civilization.bootstrap();
const OLLAMA_URL='http://127.0.0.1:11434'; const OLLAMA_EXE=path.join(process.env.LOCALAPPDATA||path.join(app.getPath('home'),'AppData','Local'),'Programs','Ollama','ollama.exe');
let ollamaReadyPromise=null;
function ensureData(){fs.mkdirSync(dataDir,{recursive:true});if(!fs.existsSync(memoryFile))fs.writeFileSync(memoryFile,JSON.stringify({memories:[]},null,2));if(!fs.existsSync(settingsFile))fs.writeFileSync(settingsFile,JSON.stringify({endpoint:OLLAMA_URL,model:DEFAULT_MODEL,internet:true,autoLearn:true},null,2));if(!fs.existsSync(webCacheFile))fs.writeFileSync(webCacheFile,JSON.stringify({pages:[]},null,2));}
function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;}} function writeJson(file,value){fs.writeFileSync(file,JSON.stringify(value,null,2));} function getSettings(){return readJson(settingsFile,{endpoint:OLLAMA_URL,model:DEFAULT_MODEL,internet:true,autoLearn:true});} function getMemory(){return readJson(memoryFile,{memories:[]});} function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function downloadFile(url,destination){return new Promise((resolve,reject)=>{const file=fs.createWriteStream(destination);https.get(url,response=>{if(response.statusCode>=300&&response.statusCode<400&&response.headers.location){file.close();fs.unlink(destination,()=>{});return downloadFile(response.headers.location,destination).then(resolve,reject);}if(response.statusCode!==200){file.close();fs.unlink(destination,()=>{});return reject(new Error(`Download HTTP ${response.statusCode}`));}response.pipe(file);file.on('finish',()=>file.close(resolve));}).on('error',err=>{file.close();fs.unlink(destination,()=>{});reject(err);});});}
function run(exe,args,options={}){return new Promise((resolve,reject)=>{const child=spawn(exe,args,{windowsHide:true,...options});let stdout='',stderr='';child.stdout?.on('data',d=>stdout+=d);child.stderr?.on('data',d=>stderr+=d);child.on('error',reject);child.on('close',code=>code===0?resolve({stdout,stderr}):reject(new Error(`${exe} exited ${code}: ${stderr||stdout}`)));});}
function ollamaInstalled(){return fs.existsSync(OLLAMA_EXE);} async function waitForOllama(timeout=120000){const t=Date.now();while(Date.now()-t<timeout){try{const r=await fetch(`${OLLAMA_URL}/api/tags`);if(r.ok)return true;}catch{}await sleep(1500);}return false;}
async function ensureOllamaAndModel(sendStatus){ensureData();try{if(!ollamaInstalled()){sendStatus?.('Устанавливаю локальный AI-движок Ollama…');const installer=path.join(dataDir,'OllamaSetup.exe');await downloadFile('https://ollama.com/download/OllamaSetup.exe',installer);await run(installer,['/VERYSILENT','/NORESTART']);try{fs.unlinkSync(installer);}catch{}}sendStatus?.('Запускаю локальный AI-движок…');try{const p=spawn(OLLAMA_EXE,['serve'],{windowsHide:true,detached:true,stdio:'ignore'});p.unref();}catch{}if(!await waitForOllama())throw new Error('Ollama не запустился на http://127.0.0.1:11434. Проверьте установку Ollama.');const tags=await(await fetch(`${OLLAMA_URL}/api/tags`)).json();if(!(tags.models||[]).some(m=>m.name===DEFAULT_MODEL)){sendStatus?.(`Скачиваю модель ${DEFAULT_MODEL}…`);await run(OLLAMA_EXE,['pull',DEFAULT_MODEL]);}writeJson(bootstrapFile,{ready:true,model:DEFAULT_MODEL,completedAt:new Date().toISOString()});sendStatus?.('ИИ готов. Интернет-поиск включён.');return true;}catch(e){writeJson(bootstrapFile,{ready:false,error:e.message});sendStatus?.(`Ошибка подготовки ИИ: ${e.message}`);return false;}}
async function ensureOllamaReady(sendStatus){if(!ollamaReadyPromise){ollamaReadyPromise=ensureOllamaAndModel(sendStatus).finally(()=>{ollamaReadyPromise=null;});}const ready=await ollamaReadyPromise;if(!ready)throw new Error('Локальный ИИ не готов. Откройте приложение снова или проверьте Ollama.');return true;}
function learnFromConversation(user,assistant,source='conversation'){const prompt=`Extract only durable, non-sensitive user preferences, goals, project facts, or explicit instructions from this material. Return JSON array of short strings. Do not infer sensitive traits. SOURCE:${source}\nTEXT:${user}\nANSWER:${assistant}`;ollama([{role:'system',content:'You are a memory curator. JSON only.'},{role:'user',content:prompt}]).then(raw=>{try{const items=JSON.parse(raw.replace(/```json|```/g,'').trim());if(Array.isArray(items)){const db=getMemory();for(const item of items.slice(0,8)){const text=String(item).trim();if(text&&!db.memories.includes(text))db.memories.push(text);}db.memories=db.memories.slice(-5000);writeJson(memoryFile,db);}}catch{}}).catch(()=>{});}
async function researchAndLearn(query){const s=getSettings();if(!s.internet)return null;try{const raw=await searchWeb(query);const db=readJson(webCacheFile,{pages:[]});db.pages.push({query,text:raw.slice(0,12000),at:new Date().toISOString()});db.pages=db.pages.slice(-100);writeJson(webCacheFile,db);return raw;}catch{return null;}}
ipcMain.handle('agent:plan',async(_,task)=>agentController.plan(task)); ipcMain.handle('permissions:list',()=>permissionManager.listPending()); ipcMain.handle('permissions:decide',(_, {id,approved})=>permissionManager.decide(id,Boolean(approved))); ipcMain.handle('agent:execute-python',async(_, {code,timeoutMs})=>agentController.executePython(code,{timeoutMs}));
ipcMain.handle('developer:inspect',()=>developerEngine.inspect()); ipcMain.handle('developer:plan',(_,task)=>developerEngine.plan(task)); ipcMain.handle('developer:validate',(_,options)=>developerEngine.validate(options||{})); ipcMain.handle('developer:run',async(_, {task,build=false})=>developerEngine.autonomousCycle({task,changes:{},build:Boolean(build)})); ipcMain.handle('developer:cycle',async(_, payload)=>developerEngine.autonomousCycle(payload||{}));
ipcMain.handle('bootstrap:status',()=>readJson(bootstrapFile,{ready:false})); ipcMain.handle('bootstrap:start',async event=>ensureOllamaReady(msg=>event.sender.send('bootstrap:progress',msg))); ipcMain.handle('settings:get',()=>getSettings()); ipcMain.handle('settings:set',(_,value)=>{const old=getSettings();const next={...old,internet:Boolean(value.internet),autoLearn:Boolean(value.autoLearn),endpoint:OLLAMA_URL,model:DEFAULT_MODEL};writeJson(settingsFile,next);return next;}); ipcMain.handle('memory:get',()=>getMemory().memories); ipcMain.handle('memory:clear',()=>{writeJson(memoryFile,{memories:[]});return [];});
ipcMain.handle('chat',async(_,payload)=>{await ensureOllamaReady();const s=getSettings();let web='';if(s.internet&&payload.allowWeb!==false)web=await researchAndLearn(payload.message)||'';const memory=getMemory().memories.slice(-100).join('\n- ');const system=`You are LocalMind, a private desktop AI assistant. You may use the web research below when present. Clearly distinguish facts from uncertain search results and never claim to have browsed if no research was provided. Persistent memory is below.\n\nMEMORY:\n- ${memory||'(empty)'}\n\nWEB RESEARCH:\n${web||'(none)'}`;const answer=await ollama([{role:'system',content:system},...(payload.history||[]),{role:'user',content:payload.message}]);if(s.autoLearn)learnFromConversation(payload.message,answer,web?'conversation+web':'conversation');return answer;}); ipcMain.handle('test',async()=>{await ensureOllamaReady();await ollama([{role:'user',content:'Reply with OK.'}]);return true;});
function createWindow(){ensureData();const win=new BrowserWindow({width:1180,height:820,minWidth:900,minHeight:650,backgroundColor:'#101318',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile('index.html');win.webContents.once('did-finish-load',()=>ensureOllamaReady(msg=>win.webContents.send('bootstrap:progress',msg)).catch(()=>{}));}
app.whenReady().then(()=>{createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});}); app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});
