const https=require('https');
const {verifyEvidence}=require('./truth-engine');
function fetchText(url,timeout=15000){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'LocalMind-AI/9.3 research',Accept:'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8'}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location)return fetchText(res.headers.location,timeout).then(resolve,reject);if(res.statusCode!==200)return reject(new Error(`HTTP ${res.statusCode}`));let data='';res.setEncoding('utf8');res.on('data',c=>{data+=c;if(data.length>800000)res.destroy();});res.on('end',()=>resolve(data));});req.setTimeout(timeout,()=>req.destroy(new Error('timeout')));req.on('error',reject);});}
function stripHtml(html){return String(html).replace(/<script[\\s\\S]*?<\\/script>/gi,' ').replace(/<style[\\s\\S]*?<\\/style>/gi,' ').replace(/<noscript[\\s\\S]*?<\\/noscript>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\\s+/g,' ').trim();}
function getJson(url,timeout=15000){return fetchText(url,timeout).then(JSON.parse);}
async function google(q){return `SOURCE: Google\\n${stripHtml(await fetchText(`https://www.google.com/search?q=${encodeURIComponent(q)}&hl=en`)).slice(0,6000)}`;}
async function bing(q){return `SOURCE: Bing\\n${stripHtml(await fetchText(`https://www.bing.com/search?q=${encodeURIComponent(q)}&setlang=en`)).slice(0,6000)}`;}
async function wikipedia(q){const j=await getJson(`https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(q)}&srlimit=5&format=json&origin=*`);return `SOURCE: Wikipedia\\n${(j.query?.search||[]).map(x=>`${x.title}: ${stripHtml(x.snippet||'')}`).join('\\n').slice(0,6000)}`;}
async function arxiv(q){return `SOURCE: arXiv\\n${stripHtml(await fetchText(`https://export.arxiv.org/api/query?search_query=all:${encodeURIComponent(q)}&start=0&max_results=5`)).slice(0,6000)}`;}
async function crossref(q){const j=await getJson(`https://api.crossref.org/works?query=${encodeURIComponent(q)}&rows=5`);return `SOURCE: Crossref\\n${(j.message?.items||[]).map(x=>`${x.title?.[0]||''} | DOI:${x.DOI||''} | ${x.published?.['date-parts']?.[0]?.join('-')||''}`).join('\\n').slice(0,6000)}`;}
async function pubmed(q){const j=await getJson(`https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=${encodeURIComponent(q)}&retmode=json&retmax=5`);const ids=j.esearchresult?.idlist||[];if(!ids.length)return 'SOURCE: PubMed\\nNo matching records';const s=await getJson(`https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=${ids.join(',')}&retmode=json`);return `SOURCE: PubMed\\n${ids.map(id=>`${s.result?.[id]?.title||''} | ${s.result?.[id]?.pubdate||''} | PMID:${id}`).join('\\n')}`;}
async function openalex(q){const j=await getJson(`https://api.openalex.org/works?search=${encodeURIComponent(q)}&per-page=5`);return `SOURCE: OpenAlex\\n${(j.results||[]).map(x=>`${x.title||''} | DOI:${x.doi||''} | ${x.publication_year||''} | cited:${x.cited_by_count||0}`).join('\\n').slice(0,6000)}`;}
async function semanticScholar(q){const url=`https://api.semanticscholar.org/graph/v1/paper/search?query=${encodeURIComponent(q)}&limit=5&fields=title,year,authors,citationCount,externalIds`;const j=await getJson(url);return `SOURCE: Semantic Scholar\\n${(j.data||[]).map(x=>`${x.title||''} | ${x.year||''} | citations:${x.citationCount||0} | DOI:${x.externalIds?.DOI||''}`).join('\\n').slice(0,6000)}`;}
async function europePmc(q){const j=await getJson(`https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=${encodeURIComponent(q)}&format=json&pageSize=5`);return `SOURCE: Europe PMC\\n${(j.resultList?.result||[]).map(x=>`${x.title||''} | ${x.pubYear||''} | PMID:${x.pmid||''} | DOI:${x.doi||''}`).join('\\n').slice(0,6000)}`;}
async function searchWeb(query){const results=await Promise.allSettled([google(query),bing(query),wikipedia(query),arxiv(query),crossref(query),pubmed(query),openalex(query),semanticScholar(query),europePmc(query)]);const parts=results.filter(r=>r.status==='fulfilled'&&r.value).map(r=>r.value);if(!parts.length)throw new Error('Не удалось получить данные из доступных источников.');const evidence=parts.join('\\n\\n---\\n\\n').slice(0,45000);let verification;try{verification=await verifyEvidence(query,evidence);}catch(e){verification={status:'UNVERIFIED',reason:`Verifier error: ${e.message}`,verifiers:{openai:false,gemini:false}};}const independentSources=parts.length;const sourceStatus=independentSources>=7?'HIGH_CORROBORATION':independentSources>=4?'CORROBORATED':'INSUFFICIENT_EVIDENCE';const strictRule='STRICT MODE: Never present a claim as established fact unless CLAIM-LEVEL VERIFICATION is VERIFIED. If status is UNVERIFIED or CONFLICTING, state that evidence is insufficient/conflicting and do not guess.';const verifierSummary=`CLAIM-LEVEL VERIFICATION: ${verification.status}\\nSOURCE CORROBORATION: ${sourceStatus}\\nINDEPENDENT SOURCE GROUPS: ${independentSources}\\nVERIFIERS: OpenAI=${verification.verifiers.openai?'OK':'MISSING'}; Gemini=${verification.verifiers.gemini?'OK':'MISSING'}\\nVERIFIER REASON: ${verification.reason}\\n${verification.claims?.length?`VERIFIED CLAIMS:\\n${verification.claims.map(c=>`- ${c.claim} [confidence ${c.confidence}] [${c.support.join(', ')}]`).join('\\n')}`:'VERIFIED CLAIMS: none'}\\n${strictRule}`;return `${verifierSummary}\\n\\n${evidence}`.slice(0,50000);}
module.exports={searchWeb};
